### PR TITLE
add a Rmarkdown example,

### PR DESCRIPTION
**Pull request by jcolomb**
not that institute is not working.

I wonder why, the lua filters are used (names are appearing correctly) but institute information is not.

### CODE REVIEW

**Comment by tarleb** [comment]
Thanks for this! The affiliations probably don't show up because the default R Markdown HTML template doesn't include the necessary variables. I don't have R Studio installed on the machine I'm on, but the following should yield better results:

```yaml
output:
  html_document:
    template: ../templates/pandoc-scholar.html
    pandoc_args:
      - "--lua-filter=../lua-filters/abstract-to-meta/abstract-to-meta.lua"
      - "--lua-filter=../lua-filters/scholarly-metadata/scholarly-metadata.lua"
```

**Comment by jcolomb** [comment]
By the way, you should definitively try rstudio ;)
see https://github.com/crsh/citr for using zotero for .md files writing!

**Comment by jcolomb** [comment]
results are better, but the reference index does not show up.
When I have time, I will try to see how rrtools deal with this (they are indeed using pandoc-scholar filter), but I think they focused on word doc outputs.

**Comment by tarleb** [comment]
> By the way, you should definitively try rstudio ;)

No worries, I do use it :) Just not on the computer that I was on when I wrote the comment.

I'll see if I can get it to work.

**Comment by jcolomb** [comment]
it seems some lua filters are missing, tried to add `- --lua-filter=../lua-filters/author-info-blocks/author-info-blocks.lua` but then the authors are not visible anymore.

any thoughts  on how to make it work?

**Comment by jcolomb** [comment]
by adding templates and filters in the right orders, now it works!

I could not get everyting to work in the html, though and the docx file has the same problem (abstract before affiliations)

**Comment by tarleb** [comment]
Great, thanks!

**Comment by aalexandersson** [comment]
Does the Rmarkdown example work for both html output and pdf output?

**Pull request merged**
